package com.example.patronuschellange.common

/**
 * class for constants tags to be used in testing to fetch compose nodes
 */
object TestTags {

    //user Item tags
    const val USER_ITEM_IMAGE_TEST_TAG = "USER_ITEM_IMAGE_TEST_TAG"
    const val USER_ITEM_NAME_TEST_TAG = "USER_ITEM_NAME_TEST_TAG"
    const val USER_ITEM_GENDER_TEST_TAG = "USER_ITEM_GENDER_TEST_TAG"
    const val USER_ITEM_PHONENUMBER_TEST_TAG = "USER_ITEM_PHONENUMBER_TEST_TAG"
    const val USER_ITEM_STICKERS_TEST_TAG = "USER_ITEM_STICKERS_TEST_TAG"
    const val USER_ITEM_DIVIDER_TEST_TAG = "USER_ITEM_DIVIDER_TEST_TAG"

    //user list tags
    const val USER_ITEM_TEST_TAG = "USER_ITEM_TEST_TAG"
    const val USER_LIST_HEADER_TEST_TAG = "USER_LIST_HEADER_TEST_TAG"


    //user details tags
    const val USER_DETAILS_HEADER_TEST_TAG = "USER_DETAILS_HEADER_TEST_TAG"
    const val USER_DETAILS_MAP_TEST_TAG = "USER_DETAILS_MAP_TEST_TAG"
    const val USER_DETAILS_IMAGE_TEST_TAG = "USER_DETAILS_IMAGE_TEST_TAG"
    const val USER_DETAILS_STICKERS_TEST_TAG = "USER_DETAILS_STICKERS_TEST_TAG"

    const val USER_DETAILS_NAME_TEST_TAG = "USER_DETAILS_NAME_TEST_TAG"
    const val USER_DETAILS_ADDRESS_TITLE_TEST_TAG = "USER_DETAILS_ADDRESS_TITLE_TEST_TAG"
    const val USER_DETAILS_ADDRESS_TEST_TAG = "USER_DETAILS_ADDRESS_TEST_TAG"
    const val USER_DETAILS_GENDER_TEST_TAG = "USER_DETAILS_GENDER_TEST_TAG"
    const val USER_DETAILS_DIVIDER_TEST_TAG = "USER_DETAILS_DIVIDER_TEST_TAG"
    const val USER_DETAILS_PHONENUMBER_TEST_TAG = "USER_DETAILS_PHONENUMBER_TEST_TAG"
}